# Generated by Django 5.0.7 on 2024-08-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0004_bill_customer_billitem_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='footwear',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
