# Generated by Django 5.0.2 on 2024-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0006_bill_customer_billitem_bill_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={'ordering': ['footwear__name']},
        ),
    ]
