# Generated by Django 5.0.2 on 2024-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0007_customuser_alter_bill_options_alter_billitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10),
        ),
    ]
