# Generated by Django 5.0.2 on 2024-08-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0012_footwear_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwear',
            name='added_by',
        ),
    ]
