# Generated by Django 5.0.2 on 2024-08-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0013_remove_footwear_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwear',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footwears', to='footwearapp.customuser'),
            preserve_default=False,
        ),
    ]
