# Generated by Django 5.0.2 on 2024-08-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0014_footwear_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwear',
            name='added_by',
        ),
    ]
